// Mock data for development and API fallbacks
import type { Playbook, Simulation, AgentMessage, Report, ChatMessage } from '../types';

export const mockPlaybooks: Playbook[] = [
  {
    id: 'pb-1',
    name: 'M&A Culture Clash',
    category: 'M&A',
    description: 'Simulate post-merger cultural integration challenges between two organizations.',
    longDescription: 'This playbook simulates the complex dynamics that emerge when two companies with different cultures merge. Agents represent key stakeholders from both organizations, including executives, middle managers, and employee representatives. The simulation explores resistance to change, power struggles, and integration strategies.',
    icon: 'Building2',
    typicalDuration: '45-60 min',
    agentCount: 8,
    rounds: 12,
    roster: [
      { role: 'Acquiring CEO', archetype: 'aggressor', description: 'Driven executive focused on rapid integration', defaultCount: 1, required: true },
      { role: 'Target CEO', archetype: 'defender', description: 'Protective of acquired company culture', defaultCount: 1, required: true },
      { role: 'Integration Lead', archetype: 'mediator', description: 'Tasked with merging operations smoothly', defaultCount: 1, required: true },
      { role: 'HR Director', archetype: 'analyst', description: 'Manages talent retention concerns', defaultCount: 1, required: false },
      { role: 'Employee Rep', archetype: 'skeptic', description: 'Voices workforce concerns', defaultCount: 2, required: false },
      { role: 'Board Member', archetype: 'influencer', description: 'Oversees merger success metrics', defaultCount: 1, required: false },
      { role: 'Union Leader', archetype: 'aggressor', description: 'Protects employee rights', defaultCount: 1, required: false },
    ],
    requiredSeeds: ['Company A Culture Doc', 'Company B Culture Doc', 'Merger Announcement'],
    objectives: ['Identify cultural friction points', 'Develop integration roadmap', 'Assess retention risks'],
    isTemplate: true,
  },
  {
    id: 'pb-2',
    name: 'Regulatory Shock Test',
    category: 'Risk',
    description: 'Test organizational response to sudden regulatory changes or compliance issues.',
    longDescription: 'Simulate how your organization responds to unexpected regulatory changes. Agents include compliance officers, legal counsel, operations leaders, and external regulators. Tests crisis response capabilities and identifies compliance gaps.',
    icon: 'ShieldAlert',
    typicalDuration: '30-45 min',
    agentCount: 6,
    rounds: 10,
    roster: [
      { role: 'Chief Compliance Officer', archetype: 'analyst', description: 'Ensures regulatory adherence', defaultCount: 1, required: true },
      { role: 'General Counsel', archetype: 'defender', description: 'Manages legal implications', defaultCount: 1, required: true },
      { role: 'Operations VP', archetype: 'aggressor', description: 'Drives operational adjustments', defaultCount: 1, required: true },
      { role: 'Regulator', archetype: 'skeptic', description: 'External oversight authority', defaultCount: 1, required: false },
      { role: 'Communications Lead', archetype: 'mediator', description: 'Manages external messaging', defaultCount: 1, required: false },
      { role: 'Business Unit Head', archetype: 'influencer', description: 'Represents affected operations', defaultCount: 1, required: false },
    ],
    requiredSeeds: ['Compliance Framework', 'Recent Regulatory Updates'],
    objectives: ['Test crisis response', 'Identify compliance gaps', 'Develop action plan'],
    isTemplate: true,
  },
  {
    id: 'pb-3',
    name: 'Competitive Response',
    category: 'Strategy',
    description: 'War-game competitor moves and develop counter-strategies.',
    longDescription: 'Simulate competitive dynamics in your market. Agents represent your company and key competitors, each with distinct strategies and market positions. Explore how different competitive moves might play out and develop robust response strategies.',
    icon: 'Swords',
    typicalDuration: '40-55 min',
    agentCount: 7,
    rounds: 15,
    roster: [
      { role: 'Your CEO', archetype: 'aggressor', description: 'Leads your company strategy', defaultCount: 1, required: true },
      { role: 'Competitor A CEO', archetype: 'aggressor', description: 'Aggressive market leader', defaultCount: 1, required: true },
      { role: 'Competitor B CEO', archetype: 'analyst', description: 'Niche player with innovation focus', defaultCount: 1, required: true },
      { role: 'Market Analyst', archetype: 'skeptic', description: 'Provides external perspective', defaultCount: 1, required: false },
      { role: 'Product Lead', archetype: 'influencer', description: 'Drives product decisions', defaultCount: 1, required: false },
      { role: 'Sales Director', archetype: 'mediator', description: 'Manages customer relationships', defaultCount: 1, required: false },
      { role: 'CFO', archetype: 'defender', description: 'Oversees financial implications', defaultCount: 1, required: false },
    ],
    requiredSeeds: ['Market Analysis', 'Competitor Profiles', 'Your Strategy Doc'],
    objectives: ['Anticipate competitor moves', 'Test strategy robustness', 'Identify market opportunities'],
    isTemplate: true,
  },
  {
    id: 'pb-4',
    name: 'Boardroom Rehearsal',
    category: 'Governance',
    description: 'Practice board presentations and anticipate tough questions.',
    longDescription: 'Rehearse your board presentation with AI agents representing different board member archetypes - the skeptic, the supporter, the detail-oriented, and the big-picture thinker. Get practice answering tough questions and refine your messaging.',
    icon: 'Users',
    typicalDuration: '25-40 min',
    agentCount: 5,
    rounds: 8,
    roster: [
      { role: 'Board Chair', archetype: 'mediator', description: 'Facilitates board discussion', defaultCount: 1, required: true },
      { role: 'Skeptical Director', archetype: 'skeptic', description: 'Challenges assumptions', defaultCount: 1, required: true },
      { role: 'Financial Expert', archetype: 'analyst', description: 'Focuses on metrics and ROI', defaultCount: 1, required: true },
      { role: 'Industry Veteran', archetype: 'influencer', description: 'Brings external experience', defaultCount: 1, required: false },
      { role: 'Founder/CEO', archetype: 'aggressor', description: 'Champions the proposal', defaultCount: 1, required: false },
    ],
    requiredSeeds: ['Board Deck', 'Financial Projections', 'Strategic Plan'],
    objectives: ['Refine messaging', 'Anticipate objections', 'Build confidence'],
    isTemplate: true,
  },
];

export const mockSimulations: Simulation[] = [
  {
    id: 'sim-1',
    name: 'TechCorp Acquisition Analysis',
    playbookId: 'pb-1',
    playbookName: 'M&A Culture Clash',
    status: 'completed',
    agents: [],
    config: { rounds: 12, environmentType: 'corporate', modelSelection: 'gpt-4', temperature: 0.7 },
    currentRound: 12,
    totalRounds: 12,
    createdAt: '2024-01-15T10:00:00Z',
    startedAt: '2024-01-15T10:05:00Z',
    completedAt: '2024-01-15T11:15:00Z',
    elapsedTime: 4200,
  },
  {
    id: 'sim-2',
    name: 'GDPR Compliance Crisis',
    playbookId: 'pb-2',
    playbookName: 'Regulatory Shock Test',
    status: 'running',
    agents: [],
    config: { rounds: 10, environmentType: 'crisis', modelSelection: 'gpt-4', temperature: 0.8 },
    currentRound: 6,
    totalRounds: 10,
    createdAt: '2024-01-16T14:00:00Z',
    startedAt: '2024-01-16T14:02:00Z',
    elapsedTime: 1800,
  },
  {
    id: 'sim-3',
    name: 'Q1 Competitive Scenario',
    playbookId: 'pb-3',
    playbookName: 'Competitive Response',
    status: 'paused',
    agents: [],
    config: { rounds: 15, environmentType: 'standard', modelSelection: 'gpt-4', temperature: 0.7 },
    currentRound: 8,
    totalRounds: 15,
    createdAt: '2024-01-17T09:00:00Z',
    startedAt: '2024-01-17T09:05:00Z',
    elapsedTime: 2400,
  },
];

export const mockAgentMessages: AgentMessage[] = [];

export const mockReport: Report = {
  id: 'report-1',
  simulationId: 'sim-1',
  simulationName: 'TechCorp Acquisition Analysis',
  generatedAt: '2024-01-15T11:15:00Z',
  executiveSummary: 'The simulation revealed significant cultural friction between the acquiring and target organizations.',
  keyRecommendations: [
    'Establish joint integration task force within 30 days',
    'Implement transparent communication strategy',
    'Prioritize top talent retention programs',
  ],
  riskRegister: [],
  scenarioMatrix: [],
  stakeholderHeatmap: [],
  fullReport: '',
};

export const mockChatMessages: ChatMessage[] = [];
