"""Interactive presentation deck exporter for simulation reports.

Generates a self-contained HTML file with embedded JavaScript for
interactive presentation of simulation results.
"""

import logging
from datetime import datetime

from app.reports.models import SimulationReport
from app.simulation.models import SimulationState

logger = logging.getLogger(__name__)


class InteractiveDeckExporter:
    """Exports simulation reports as interactive HTML presentation decks."""

    def __init__(
        self,
        logo_url: str | None = None,
        primary_color: str = "#3B82F6",
        company_name: str = "ScenarioLab",
    ):
        self.logo_url = logo_url
        self.primary_color = primary_color
        self.company_name = company_name

    def export_interactive_deck(
        self,
        report: SimulationReport,
        simulation_state: SimulationState | None = None,
    ) -> str:
        """Generate a self-contained interactive HTML presentation.

        Args:
            report: The simulation report to export
            simulation_state: Optional simulation state for additional context

        Returns:
            Complete HTML string with embedded CSS and JavaScript
        """
        html = self._generate_html(report, simulation_state)
        return html

    def _generate_html(
        self,
        report: SimulationReport,
        simulation_state: SimulationState | None,
    ) -> str:
        """Generate the complete HTML document."""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self._escape_html(report.simulation_name)} - Report</title>
    <style>
{self._generate_css()}
    </style>
</head>
<body>
    <div class="theme-toggle">
        <button onclick="toggleTheme()" id="themeBtn">
            Toggle Dark/Light
        </button>
    </div>
    <div class="container">
{self._generate_cover_section(report)}
{self._generate_agent_personas(report, simulation_state)}
{self._generate_risk_register(report)}
{self._generate_scenario_matrix(report)}
{self._generate_stakeholder_heatmap(report)}
{self._generate_key_findings(report)}
{self._generate_recommendations(report)}
{self._generate_monte_carlo(report)}
    </div>
    <footer>
        Generated by {self._escape_html(self.company_name)} on {
            datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        }
    </footer>
    <script>
{self._generate_javascript()}
    </script>
</body>
</html>"""

    def _generate_css(self) -> str:
        """Generate inline CSS styles."""
        return f"""        :root {{
            --primary-color: {self.primary_color};
            --bg-color: #ffffff;
            --text-color: #1f2937;
            --card-bg: #f9fafb;
            --border-color: #e5e7eb;
            --shadow: 0 1px 3px rgba(0,0,0,0.1);
        }}
        [data-theme="dark"] {{
            --bg-color: #111827;
            --text-color: #f9fafb;
            --card-bg: #1f2937;
            --border-color: #374151;
            --shadow: 0 1px 3px rgba(0,0,0,0.3);
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                Oxygen, Ubuntu, sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            line-height: 1.6;
            transition: background-color 0.3s, color 0.3s;
        }}
        .theme-toggle {{
            position: fixed;
            top: 1rem;
            right: 1rem;
            z-index: 1000;
        }}
        .theme-toggle button {{
            background: var(--primary-color);
            color: white;
            border: none;
            padding: 0.5rem 1rem;
            border-radius: 0.375rem;
            cursor: pointer;
            font-size: 0.875rem;
        }}
        .theme-toggle button:hover {{
            opacity: 0.9;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem 1rem;
        }}
        .section {{
            margin-bottom: 3rem;
            background: var(--card-bg);
            border-radius: 0.5rem;
            padding: 1.5rem;
            box-shadow: var(--shadow);
        }}
        h1 {{
            font-size: 2.25rem;
            font-weight: 700;
            margin-bottom: 1rem;
            color: var(--primary-color);
        }}
        h2 {{
            font-size: 1.5rem;
            font-weight: 600;
            margin-bottom: 1rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid var(--primary-color);
        }}
        h3 {{ font-size: 1.125rem; font-weight: 600; margin-bottom: 0.5rem; }}
        p {{ margin-bottom: 1rem; }}
        .meta {{
            color: #6b7280;
            font-size: 0.875rem;
            margin-bottom: 0.5rem;
        }}
        [data-theme="dark"] .meta {{ color: #9ca3af; }}
        .tabs {{
            display: flex;
            gap: 0.5rem;
            margin-bottom: 1rem;
            flex-wrap: wrap;
        }}
        .tab {{
            padding: 0.5rem 1rem;
            background: transparent;
            border: 1px solid var(--border-color);
            border-radius: 0.375rem;
            cursor: pointer;
            color: var(--text-color);
            font-size: 0.875rem;
        }}
        .tab.active {{
            background: var(--primary-color);
            color: white;
            border-color: var(--primary-color);
        }}
        .tab-content {{ display: none; }}
        .tab-content.active {{ display: block; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1rem 0;
        }}
        th, td {{
            padding: 0.75rem;
            text-align: left;
            border-bottom: 1px solid var(--border-color);
        }}
        th {{
            background: var(--primary-color);
            color: white;
            font-weight: 600;
        }}
        tr:hover {{ background: rgba(59, 130, 246, 0.1); }}
        .severity-critical {{ color: #dc2626; font-weight: bold; }}
        .severity-high {{ color: #ea580c; font-weight: bold; }}
        .severity-medium {{ color: #d97706; }}
        .severity-low {{ color: #16a34a; }}
        .agent-card {{
            background: var(--bg-color);
            border: 1px solid var(--border-color);
            border-radius: 0.5rem;
            padding: 1rem;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }}
        .agent-card:hover {{
            transform: translateY(-2px);
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .agent-cards {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
            gap: 1rem;
        }}
        .agent-role {{
            font-size: 0.75rem;
            color: var(--primary-color);
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}
        .filter-bar {{
            display: flex;
            gap: 1rem;
            margin-bottom: 1rem;
            flex-wrap: wrap;
            align-items: center;
        }}
        .filter-bar input, .filter-bar select {{
            padding: 0.5rem;
            border: 1px solid var(--border-color);
            border-radius: 0.375rem;
            background: var(--bg-color);
            color: var(--text-color);
        }}
        .filter-bar input {{
            flex: 1;
            min-width: 200px;
        }}
        .expandable {{
            cursor: pointer;
        }}
        .expandable .content {{
            display: none;
            padding: 1rem;
            background: var(--bg-color);
            border-radius: 0.375rem;
            margin-top: 0.5rem;
        }}
        .expandable.expanded .content {{
            display: block;
        }}
        .expandable::before {{
            content: '▶ ';
            font-size: 0.75rem;
        }}
        .expandable.expanded::before {{
            content: '▼ ';
        }}
        .heatmap-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
            gap: 0.5rem;
        }}
        .heatmap-cell {{
            padding: 1rem;
            border-radius: 0.375rem;
            text-align: center;
        }}
        .support-strong {{ background: #dcfce7; color: #166534; }}
        .support-moderate {{ background: #bbf7d0; color: #166534; }}
        .neutral {{ background: #fef3c7; color: #92400e; }}
        .oppose-moderate {{ background: #fed7aa; color: #9a3412; }}
        .oppose-strong {{ background: #fecaca; color: #991b1b; }}
        [data-theme="dark"] .support-strong {{ background: #166534; }}
        [data-theme="dark"] .support-moderate {{ background: #15803d; }}
        [data-theme="dark"] .neutral {{ background: #854d0e; }}
        [data-theme="dark"] .oppose-moderate {{ background: #c2410c; }}
        [data-theme="dark"] .oppose-strong {{ background: #b91c1c; }}
        .chart-container {{
            width: 100%;
            height: 200px;
            position: relative;
        }}
        .bar-chart {{
            display: flex;
            align-items: flex-end;
            height: 100%;
            gap: 1rem;
            padding: 1rem;
        }}
        .bar {{
            flex: 1;
            background: var(--primary-color);
            border-radius: 0.25rem 0.25rem 0 0;
            position: relative;
            min-height: 10px;
            transition: height 0.3s;
        }}
        .bar-label {{
            position: absolute;
            bottom: -1.5rem;
            left: 50%;
            transform: translateX(-50%);
            font-size: 0.75rem;
            white-space: nowrap;
        }}
        .bar-value {{
            position: absolute;
            top: -1.5rem;
            left: 50%;
            transform: translateX(-50%);
            font-size: 0.75rem;
            font-weight: 600;
        }}
        footer {{
            text-align: center;
            padding: 2rem;
            color: #6b7280;
            font-size: 0.875rem;
        }}
        [data-theme="dark"] footer {{ color: #9ca3af; }}
        @media (max-width: 768px) {{
            .container {{ padding: 1rem; }}
            h1 {{ font-size: 1.5rem; }}
            h2 {{ font-size: 1.25rem; }}
            .agent-cards {{
                grid-template-columns: 1fr;
            }}
            .filter-bar {{
                flex-direction: column;
                align-items: stretch;
            }}
            .filter-bar input {{
                min-width: 100%;
            }}
        }}
        @media print {{
            .theme-toggle {{ display: none; }}
            .section {{ break-inside: avoid; }}
        }}"""

    def _generate_javascript(self) -> str:
        """Generate inline JavaScript for interactivity."""
        return """        function toggleTheme() {
            const body = document.body;
            const current = body.getAttribute('data-theme');
            body.setAttribute('data-theme', current === 'dark' ? 'light' : 'dark');
            localStorage.setItem('theme', body.getAttribute('data-theme'));
        }
        (function() {
            const saved = localStorage.getItem('theme');
            if (saved) document.body.setAttribute('data-theme', saved);
        })();
        function showTab(sectionId, tabName) {
            const section = document.getElementById(sectionId);
            section.querySelectorAll('.tab').forEach(t => {
                t.classList.remove('active');
            });
            section.querySelectorAll('.tab-content').forEach(c => {
                c.classList.remove('active');
            });
            section.querySelector('[onclick*="' + tabName + '"]')
                .classList.add('active');
            document.getElementById(tabName).classList.add('active');
        }
        function toggleExpand(element) {
            element.classList.toggle('expanded');
        }
        function sortTable(tableId, column) {
            const table = document.getElementById(tableId);
            const tbody = table.querySelector('tbody');
            const rows = Array.from(tbody.querySelectorAll('tr'));
            const dir = table.getAttribute('data-sort-dir') === 'asc' ? -1 : 1;
            rows.sort((a, b) => {
                const aVal = a.cells[column].textContent.trim();
                const bVal = b.cells[column].textContent.trim();
                return aVal.localeCompare(bVal, undefined, {numeric: true}) * dir;
            });
            table.setAttribute('data-sort-dir', dir === 1 ? 'asc' : 'desc');
            rows.forEach(row => tbody.appendChild(row));
        }
        function filterTable(tableId, inputId) {
            const filter = document.getElementById(inputId).value.toLowerCase();
            const table = document.getElementById(tableId);
            const rows = table.querySelectorAll('tbody tr');
            rows.forEach(row => {
                const text = row.textContent.toLowerCase();
                row.style.display = text.includes(filter) ? '' : 'none';
            });
        }
        function filterBySeverity(tableId, selectId) {
            const severity = document.getElementById(selectId).value;
            const table = document.getElementById(tableId);
            const rows = table.querySelectorAll('tbody tr');
            rows.forEach(row => {
                if (!severity || row.cells[3].textContent.toLowerCase()
                        .includes(severity)) {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        }"""

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#39;")
        )

    def _generate_cover_section(self, report: SimulationReport) -> str:
        """Generate the cover section."""
        logo_html = ""
        if self.logo_url:
            logo_html = f'<img src="{self._escape_html(self.logo_url)}" alt="Logo" style="max-height: 60px; margin-bottom: 1rem;">'  # noqa: E501

        summary_text = ""
        if report.executive_summary:
            summary_text = report.executive_summary.summary_text[:500]
            if len(report.executive_summary.summary_text) > 500:
                summary_text += "..."

        return f"""        <div class="section" id="cover">
            {logo_html}
            <h1>{self._escape_html(report.simulation_name)}</h1>
            <p class="meta">Report ID: {self._escape_html(report.id)}</p>
            <p class="meta">Simulation ID: {
                self._escape_html(report.simulation_id)
            }</p>
            <p class="meta">Status: {self._escape_html(report.status)}</p>
            <p class="meta">Generated: {self._escape_html(report.created_at)}</p>
            <div style="margin-top: 1.5rem;">
                <h3>Executive Summary</h3>
                <p>{self._escape_html(summary_text)}</p>
            </div>
        </div>"""

    def _generate_agent_personas(
        self,
        report: SimulationReport,
        simulation_state: SimulationState | None,
    ) -> str:
        """Generate agent persona cards section."""
        agents_html = ""

        if simulation_state and simulation_state.agents:
            for agent in simulation_state.agents:
                stance = agent.current_stance[:100] if agent.current_stance else ""
                if len(agent.current_stance) > 100 if agent.current_stance else False:
                    stance += "..."
                agents_html += f"""                <div class="agent-card" onclick="toggleExpand(this)">
                    <div class="agent-role">{self._escape_html(agent.archetype_id)}</div>
                    <h3>{self._escape_html(agent.name)}</h3>
                    <p class="meta">Current Stance: {self._escape_html(stance)}</p>
                    <div class="content">
                        <p><strong>Persona:</strong> {
                            self._escape_html(agent.persona_prompt[:200])
                        }...</p>
                        <p><strong>Coalition Members:</strong> {
                            len(agent.coalition_members)
                        }</p>
                        <p><strong>Vote History:</strong> {
                            len(agent.vote_history)
                        } votes</p>
                    </div>
                </div>
"""
        elif report.stakeholder_heatmap:
            for sh in report.stakeholder_heatmap.stakeholders:
                agents_html += f"""                <div class="agent-card">
                    <div class="agent-role">{self._escape_html(sh.role)}</div>
                    <h3>{self._escape_html(sh.stakeholder)}</h3>
                    <p class="meta">Position: {self._escape_html(
                        sh.position.replace('_', ' ').title()
                    )}</p>
                    <p class="meta">Influence: {sh.influence:.0%}</p>
                    <p class="meta">Support: {sh.support_level:+.0%}</p>
                </div>
"""
        else:
            agents_html = "<p>No agent data available</p>"

        return f"""        <div class="section" id="agents">
            <h2>Agent Personas</h2>
            <p class="meta">Click cards to expand details</p>
            <div class="agent-cards">
{agents_html}
            </div>
        </div>"""

    def _generate_risk_register(self, report: SimulationReport) -> str:
        """Generate interactive risk register section."""
        if not report.risk_register or not report.risk_register.items:
            return """        <div class="section" id="risks">
            <h2>Risk Register</h2>
            <p>No risks identified</p>
        </div>"""

        table_id = "risk-table"
        filter_id = "risk-filter"
        severity_id = "severity-filter"

        rows_html = ""
        for risk in report.risk_register.items:
            severity_class = f"severity-{risk.impact}"
            rows_html += f"""                    <tr>
                        <td>{self._escape_html(risk.risk_id)}</td>
                        <td>{self._escape_html(risk.description[:60])}...</td>
                        <td>{risk.probability:.0%}</td>
                        <td class="{severity_class}">{
                            risk.impact.upper()
                        }</td>
                        <td>{self._escape_html(risk.owner)}</td>
                        <td>{self._escape_html(risk.mitigation[:40])}...</td>
                    </tr>
"""

        return f"""        <div class="section" id="risks">
            <h2>Risk Register</h2>
            <p class="meta">Total Risks: {len(report.risk_register.items)}</p>
            <div class="filter-bar">
                <input type="text" id="{filter_id}"
                    placeholder="Search risks..."
                    oninput="filterTable('{table_id}', '{filter_id}')">
                <select id="{severity_id}"
                    onchange="filterBySeverity('{table_id}', '{severity_id}')">
                    <option value="">All Severities</option>
                    <option value="critical">Critical</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                </select>
            </div>
            <table id="{table_id}" data-sort-dir="asc">
                <thead>
                    <tr>
                        <th onclick="sortTable('{table_id}', 0)">ID</th>
                        <th onclick="sortTable('{table_id}', 1)">Desc</th>
                        <th onclick="sortTable('{table_id}', 2)">Prob</th>
                        <th onclick="sortTable('{table_id}', 3)">Impact</th>
                        <th onclick="sortTable('{table_id}', 4)">Owner</th>
                        <th onclick="sortTable('{table_id}', 5)">Mitigate</th>
                    </tr>
                </thead>
                <tbody>
{rows_html}
                </tbody>
            </table>
        </div>"""

    def _generate_scenario_matrix(self, report: SimulationReport) -> str:
        """Generate scenario matrix section."""
        if not report.scenario_matrix or not report.scenario_matrix.scenarios:
            return """        <div class="section" id="scenarios">
            <h2>Scenario Matrix</h2>
            <p>No scenarios defined</p>
        </div>"""

        tabs_html = ""
        contents_html = ""

        for i, scenario in enumerate(report.scenario_matrix.scenarios):
            active = "active" if i == 0 else ""
            tabs_html += f"""                <button class="tab {active}"
                    onclick="showTab('scenarios', 'scenario-{i}')">{
                        self._escape_html(scenario.scenario_name[:20])
                    }</button>
"""
            drivers_html = ""
            for driver in scenario.key_drivers:
                drivers_html += f"<li>{self._escape_html(driver)}</li>"

            outcomes_html = ""
            for dim, outcome in scenario.outcomes.items():
                outcomes_html += f"""                        <tr>
                            <td>{self._escape_html(dim)}</td>
                            <td>{self._escape_html(outcome)}</td>
                        </tr>
"""

            prob_min, prob_max = scenario.probability_range
            contents_html += f"""                <div id="scenario-{i}" class="tab-content {active}">
                    <h3>{self._escape_html(scenario.scenario_name)}</h3>
                    <p class="meta">Probability: {prob_min:.0%} - {prob_max:.0%}</p>
                    <p class="meta">Confidence: {scenario.confidence_interval:.0%}</p>
                    <p>{self._escape_html(scenario.description)}</p>
                    <h4>Key Drivers</h4>
                    <ul>{drivers_html}</ul>
                    <h4>Outcomes by Dimension</h4>
                    <table>
                        <tr><th>Dimension</th><th>Outcome</th></tr>
{outcomes_html}
                    </table>
                </div>
"""

        return f"""        <div class="section" id="scenarios">
            <h2>Scenario Matrix</h2>
            <div class="tabs">
{tabs_html}
            </div>
{contents_html}
        </div>"""

    def _generate_stakeholder_heatmap(self, report: SimulationReport) -> str:
        """Generate stakeholder heatmap section."""
        if not report.stakeholder_heatmap:
            return """        <div class="section" id="stakeholders">
            <h2>Stakeholder Heatmap</h2>
            <p>No stakeholder data available</p>
        </div>"""

        cells_html = ""
        for sh in report.stakeholder_heatmap.stakeholders:
            if sh.support_level >= 0.5:
                css_class = "support-strong"
            elif sh.support_level >= 0.2:
                css_class = "support-moderate"
            elif sh.support_level >= -0.2:
                css_class = "neutral"
            elif sh.support_level >= -0.5:
                css_class = "oppose-moderate"
            else:
                css_class = "oppose-strong"

            cells_html += f"""                    <div class="heatmap-cell {css_class}">
                        <strong>{self._escape_html(sh.stakeholder)}</strong>
                        <br><small>{self._escape_html(sh.role)}</small>
                        <br>Influence: {sh.influence:.0%}
                    </div>
"""

        return f"""        <div class="section" id="stakeholders">
            <h2>Stakeholder Heatmap</h2>
            <p class="meta">Support Level: Green = Support, Yellow = Neutral,
                Red = Oppose</p>
            <div class="heatmap-grid">
{cells_html}
            </div>
        </div>"""

    def _generate_key_findings(self, report: SimulationReport) -> str:
        """Generate key findings section."""
        if not report.executive_summary:
            return """        <div class="section" id="findings">
            <h2>Key Findings</h2>
            <p>No findings available</p>
        </div>"""

        findings_html = ""
        for i, finding in enumerate(report.executive_summary.key_findings):
            findings_html += f"""                <div class="expandable" onclick="toggleExpand(this)">
                    <strong>Finding {i + 1}:</strong> {
                        self._escape_html(finding[:80])
                    }...
                    <div class="content">
                        <p>{self._escape_html(finding)}</p>
                    </div>
                </div>
"""

        return f"""        <div class="section" id="findings">
            <h2>Key Findings</h2>
{findings_html}
        </div>"""

    def _generate_recommendations(self, report: SimulationReport) -> str:
        """Generate prioritized recommendations section."""
        if not report.executive_summary:
            return """        <div class="section" id="recommendations">
            <h2>Recommendations</h2>
            <p>No recommendations available</p>
        </div>"""

        recs_html = ""
        for rec in report.executive_summary.recommendations:
            priority_class = f"severity-{rec.priority}"
            recs_html += f"""                <div style="margin-bottom: 1rem; padding: 1rem;
                    border-left: 4px solid var(--primary-color);
                    background: var(--bg-color); border-radius: 0.25rem;">
                    <h3>{self._escape_html(rec.title)}
                        <span class="{priority_class}">({rec.priority.upper()})</span>
                    </h3>
                    <p>{self._escape_html(rec.description)}</p>
                    <p class="meta"><strong>Rationale:</strong> {
                        self._escape_html(rec.rationale)
                    }</p>
                </div>
"""

        return f"""        <div class="section" id="recommendations">
            <h2>Recommendations</h2>
{recs_html}
        </div>"""

    def _generate_monte_carlo(self, report: SimulationReport) -> str:
        """Generate Monte Carlo visualization section."""
        # Check if Monte Carlo data is available in results_summary
        mc_data = None
        if hasattr(report, "results_summary") and report.results_summary:
            mc_data = report.results_summary.get("monte_carlo")

        if not mc_data:
            # Generate placeholder bars
            bars_html = ""
            outcomes = [
                ("Best Case", 15),
                ("Expected", 45),
                ("Downside", 30),
                ("Worst Case", 10),
            ]
            for name, value in outcomes:
                bars_html += f"""                    <div class="bar" style="height: {value}%">
                        <span class="bar-value">{value}%</span>
                        <span class="bar-label">{name}</span>
                    </div>
"""
            return f"""        <div class="section" id="monte-carlo">
            <h2>Outcome Distribution</h2>
            <p class="meta">Simulated outcome probabilities</p>
            <div class="chart-container">
                <div class="bar-chart">
{bars_html}
                </div>
            </div>
        </div>"""

        # Use actual Monte Carlo data if available
        bars_html = ""
        for outcome in mc_data.get("outcomes", []):
            name = outcome.get("name", "Unknown")
            prob = outcome.get("probability", 0) * 100
            bars_html += f"""                    <div class="bar" style="height: {prob}%">
                        <span class="bar-value">{prob:.0f}%</span>
                        <span class="bar-label">{self._escape_html(name)}</span>
                    </div>
"""
        return f"""        <div class="section" id="monte-carlo">
            <h2>Monte Carlo Analysis</h2>
            <p class="meta">Based on {mc_data.get('iterations', 1000)} iterations</p>
            <div class="chart-container">
                <div class="bar-chart">
{bars_html}
                </div>
            </div>
        </div>"""


async def export_interactive_deck(
    report: SimulationReport,
    simulation_state: SimulationState | None = None,
    logo_url: str | None = None,
    primary_color: str = "#3B82F6",
    company_name: str = "ScenarioLab",
) -> str:
    """Export report as interactive HTML deck.

    Args:
        report: The simulation report to export
        simulation_state: Optional simulation state for additional context
        logo_url: Optional URL for company logo
        primary_color: Primary color for styling (default: blue)
        company_name: Company name for branding

    Returns:
        Complete HTML string
    """
    exporter = InteractiveDeckExporter(
        logo_url=logo_url,
        primary_color=primary_color,
        company_name=company_name,
    )
    return exporter.export_interactive_deck(report, simulation_state)
