"""Core data models for the Multi-Agent Simulation Engine."""

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


def _utc_now_iso() -> str:
    """Return current UTC time as ISO string (timezone-aware)."""
    return datetime.now(timezone.utc).isoformat()


class SimulationStatus(str, Enum):
    """Simulation lifecycle statuses."""

    CONFIGURING = "configuring"
    READY = "ready"
    RUNNING = "running"
    PAUSED = "paused"
    GENERATING_REPORT = "generating_report"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class EnvironmentType(str, Enum):
    """Types of simulation environments."""

    BOARDROOM = "boardroom"
    WAR_ROOM = "war_room"
    NEGOTIATION = "negotiation"
    INTEGRATION = "integration"


class AgentConfig(BaseModel):
    """Configuration for a single agent in the simulation."""

    id: str = ""
    name: str
    archetype_id: str
    customization: dict = {}  # Override archetype defaults

    def model_post_init(self, __context):
        """Generate ID if not provided."""
        if not self.id:
            self.id = str(uuid.uuid4())


class SimulationConfig(BaseModel):
    """Configuration for a simulation session."""

    id: str = ""
    name: str
    description: str = ""
    playbook_id: str | None = None
    environment_type: EnvironmentType = EnvironmentType.BOARDROOM
    agents: list[AgentConfig] = []
    total_rounds: int = 10
    seed_id: str | None = None  # Legacy single seed reference
    seed_ids: list[str] = []  # References to uploaded seed materials
    parameters: dict = {}  # Additional parameters

    def model_post_init(self, __context):
        """Generate ID if not provided."""
        if not self.id:
            self.id = str(uuid.uuid4())


class AgentState(BaseModel):
    """Runtime state of an agent in the simulation."""

    id: str
    name: str
    archetype_id: str
    persona_prompt: str  # Full system prompt
    current_stance: str = ""  # Current position/stance summary
    coalition_members: list[str] = []
    vote_history: list[dict] = []


class SimulationMessage(BaseModel):
    """A message generated by an agent during simulation."""

    id: str = ""
    round_number: int
    phase: str  # Current phase within the round
    agent_id: str
    agent_name: str
    agent_role: str
    content: str
    message_type: str = "statement"  # statement, question, objection, etc.
    visibility: str = "public"  # public, private, coalition
    target_agents: list[str] = []  # For private messages
    timestamp: str = ""

    def model_post_init(self, __context):
        """Generate ID and timestamp if not provided."""
        if not self.id:
            self.id = str(uuid.uuid4())
        if not self.timestamp:
            self.timestamp = _utc_now_iso()


class RoundState(BaseModel):
    """State of a single round in the simulation."""

    round_number: int
    phase: str
    messages: list[SimulationMessage] = []
    decisions: list[dict] = []
    phase_complete: bool = False


class SimulationState(BaseModel):
    """Complete state of a simulation session."""

    config: SimulationConfig
    status: SimulationStatus = SimulationStatus.CONFIGURING
    current_round: int = 0
    current_phase: str = ""
    agents: list[AgentState] = []
    rounds: list[RoundState] = []
    created_at: str = ""
    updated_at: str = ""
    results_summary: dict = {}
    # Hybrid inference: per-agent style exemplars (response/vote/stance) after cloud
    # priming rounds — persisted so pause/resume and cold reload keep local calibration.
    hybrid_exemplar_snapshot: dict[str, dict[str, str]] | None = None

    def model_post_init(self, __context):
        """Generate timestamps if not provided."""
        now = _utc_now_iso()
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now


class VoteResult(BaseModel):
    """Result of a voting phase."""

    agent_id: str
    agent_name: str
    vote: str  # "for", "against", "abstain"
    reasoning: str


class SimulationSummary(BaseModel):
    """Summary of a simulation for listing."""

    id: str
    name: str
    status: SimulationStatus
    environment_type: EnvironmentType
    current_round: int
    total_rounds: int
    agent_count: int
    created_at: str
    updated_at: str


class SimulationCreateRequest(BaseModel):
    """Request to create a new simulation."""

    name: str
    description: str = ""
    playbook_id: str | None = None
    environment_type: EnvironmentType = EnvironmentType.BOARDROOM
    agents: list[AgentConfig] = []
    total_rounds: int = 10
    seed_id: str | None = None  # Legacy single seed reference
    seed_ids: list[str] = []  # Multiple seed document references
    parameters: dict = {}


class DualCreateRequest(BaseModel):
    """Create two simulations in one request; if the second fails, the first is removed."""

    scenario_a: SimulationCreateRequest
    scenario_b: SimulationCreateRequest


class DualCreateResponse(BaseModel):
    """Created pair for scenario comparison."""

    simulation_a: SimulationState
    simulation_b: SimulationState


class DualRunPresetWarning(BaseModel):
    """Structured warning from dual-run preset merge/validation."""

    code: str
    message: str
    level: str | None = None
    metadata: dict[str, Any] | None = None


class DualRunPresetCreateResponse(BaseModel):
    """Compare flow: preset merge plus created pair (same rollback semantics as /dual-create)."""

    batch_parent_id: str
    warnings: list[DualRunPresetWarning] = Field(default_factory=list)
    simulation_a: SimulationState
    simulation_b: SimulationState


class SimulationUpdateRequest(BaseModel):
    """Request to update a simulation configuration."""

    name: str | None = None
    description: str | None = None
    agents: list[AgentConfig] | None = None
    total_rounds: int | None = None
    parameters: dict | None = None
